language: python
python:
    - 2.7

install:
  - pip install theano
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
  - python setup.py install

script:
  - DEEPX_BACKED='theano' nosetests tests/
  - DEEPX_BACKED='tensorflow' nosetests tests/
