language: python
python:
    - 2.7

# Setup anaconda
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  # Coverage packages are on my binstar channel
  #- conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install coveralls
  - pip install theano
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
  - python setup.py install

# Run test
#script:
  #- nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
#after_success:
  #- coveralls --config_file .coveragerc
  #
after_success:
  coveralls

script:
  - DEEPX_BACKEND='theano' nosetests --with-coverage --cover-package=deepx --logging-level=INFO tests/
  - DEEPX_BACKEND='tensorflow' nosetests --with-coverage --cover-package=deepx --logging-level=INFO tests/
